CREATE TABLE `bx_log_elems` (
    `ID` INT(11) NOT NULL AUTO_INCREMENT,
    `EVENT` VARCHAR(65536) NOT NULL,
    `IBLOCK_ID` INT(11),
    `NAME` VARCHAR(65536) NOT NULL,
    `EVENT` VARCHAR(65536) NOT NULL,
    `DATE_AND_TIME_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `DATE_RECORD` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `USER_ID` INT(11) DEFAULT ,
    PRIMARY KEY(ID)
);